import type { Hero, Upgrade, Skill, Artifact } from "../types/game";

export const INITIAL_HERO: Hero = {
  level: 1,
  exp: 0,
  nextLevelExp: 100,
  currentHp: 100,
  maxHp: 100,
  attack: 10,
  defense: 2,
  attackSpeed: 1.2,
  critChance: 0.1,
  critDamage: 1.5,
  regen: 1,
  weaponLvl: 1,
  armorLvl: 1,
  bootsLvl: 1,
};

export const INITIAL_UPGRADES: Upgrade[] = [
  {
    id: "upg_att",
    name: "Physical Training",
    description: "Increases base attack by 2",
    cost: 15,
    costMultiplier: 1.15,
    currentLevel: 0,
    baseValue: 0,
    scaling: 2,
    type: "attack",
  },
  {
    id: "upg_hp",
    name: "Endurance Training",
    description: "Increases max health by 15",
    cost: 20,
    costMultiplier: 1.15,
    currentLevel: 0,
    baseValue: 0,
    scaling: 15,
    type: "hp",
  },
  {
    id: "upg_regen",
    name: "Rejuvenation",
    description: "Increases passive regeneration by 0.5 HP/s",
    cost: 30,
    costMultiplier: 1.2,
    currentLevel: 0,
    baseValue: 0,
    scaling: 0.5,
    type: "regen",
  },
  {
    id: "upg_crit",
    name: "Focus Training",
    description: "Increases critical strike chance by 1%",
    cost: 50,
    costMultiplier: 1.25,
    currentLevel: 0,
    baseValue: 0,
    scaling: 0.01,
    type: "crit",
  },
  {
    id: "upg_speed",
    name: "Agility Training",
    description: "Reduces attack interval by 3%",
    cost: 60,
    costMultiplier: 1.25,
    currentLevel: 0,
    baseValue: 0,
    scaling: 0.03,
    type: "speed",
  },
  {
    id: "upg_wpn",
    name: "Forge Weapon",
    description: "Greatly increases attack & upgrades 3D sword visual",
    cost: 100,
    costMultiplier: 1.4,
    currentLevel: 1,
    baseValue: 0,
    scaling: 5,
    type: "weapon",
  },
  {
    id: "upg_arm",
    name: "Reinforce Armor",
    description: "Increases defense & upgrades 3D shield visual",
    cost: 100,
    costMultiplier: 1.4,
    currentLevel: 1,
    baseValue: 0,
    scaling: 3,
    type: "armor",
  },
  {
    id: "upg_bts",
    name: "Heavy Boots",
    description: "Slightly reduces attack speed interval & increases speed",
    cost: 80,
    costMultiplier: 1.35,
    currentLevel: 1,
    baseValue: 0,
    scaling: 0.02,
    type: "boots",
  },
];

export const INITIAL_SKILLS: Skill[] = [
  {
    id: "skl_slash",
    name: "Whirlwind Slash",
    description: "Unleashes a rapid series of attacks, dealing 4x weapon damage instantly.",
    cooldown: 12,
    currentCooldown: 0,
    duration: 0.5,
    activeDuration: 0,
    cost: 0,
    level: 1,
    costMultiplier: 1.5,
    effectType: "damage",
    effectValue: 4,
    unlockedAt: 1,
  },
  {
    id: "skl_heal",
    name: "Holy Restoration",
    description: "Heals the Hero for 50% of their Max HP instantly.",
    cooldown: 20,
    currentCooldown: 0,
    duration: 0.1,
    activeDuration: 0,
    cost: 0,
    level: 1,
    costMultiplier: 1.5,
    effectType: "heal",
    effectValue: 0.5,
    unlockedAt: 3,
  },
  {
    id: "skl_frenzy",
    name: "Blood Frenzy",
    description: "Enter a battle trance! Increases attack speed by 100% for 6 seconds.",
    cooldown: 30,
    currentCooldown: 0,
    duration: 6,
    activeDuration: 0,
    cost: 0,
    level: 1,
    costMultiplier: 1.5,
    effectType: "speed",
    effectValue: 2,
    unlockedAt: 5,
  },
  {
    id: "skl_greed",
    name: "Midas Touch",
    description: "Enchants weapon to yield 300% more Gold from defeated enemies for 8 seconds.",
    cooldown: 45,
    currentCooldown: 0,
    duration: 8,
    activeDuration: 0,
    cost: 0,
    level: 1,
    costMultiplier: 1.5,
    effectType: "goldMultiplier",
    effectValue: 3,
    unlockedAt: 8,
  },
];

export const INITIAL_ARTIFACTS: Artifact[] = [
  {
    id: "art_sigil",
    name: "Sigil of Ruin",
    description: "Increases all damage dealt by 20% per level.",
    level: 0,
    cost: 10,
    costMultiplier: 1.8,
    effectType: "dmg_mult",
    effectValue: 0.2,
  },
  {
    id: "art_coin",
    name: "Greedy Goblet",
    description: "Increases all gold acquired by 25% per level.",
    level: 0,
    cost: 15,
    costMultiplier: 1.8,
    effectType: "gold_mult",
    effectValue: 0.25,
  },
  {
    id: "art_tome",
    name: "Chronicles of EXP",
    description: "Increases experience gained by 15% per level.",
    level: 0,
    cost: 10,
    costMultiplier: 1.8,
    effectType: "exp_mult",
    effectValue: 0.15,
  },
  {
    id: "art_slayer",
    name: "Titan Slayer",
    description: "Increases damage dealt to bosses by 30% per level.",
    level: 0,
    cost: 20,
    costMultiplier: 2.0,
    effectType: "boss_dmg",
    effectValue: 0.3,
  },
];

export const MONSTER_NAMES = {
  goblin: ["Cave Imp", "Goblin Thief", "Gringo the Goblin", "Goblin Chieftain"],
  skeleton: ["Rattling Bones", "Skeleton Archer", "Decayed Guardian", "Lich Squire"],
  orc: ["Orc Grunt", "Fierce Berserker", "Orc Marauder", "Ironhide Orc"],
  demon: ["Hellspawn", "Fiery Imp", "Abyssal Terror", "Demon Overlord"],
  dragon: ["Baby Hatchling", "Wyvern Outcast", "Emerald Drake", "Ancient Red Dragon"],
};
